apiVersion: v1
kind: Service
metadata:
  name: hugo-site
  spec: merge-intervals
  selector:
    app: merge-intervals
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
