name: Build and test Go
on: push
jobs:
  build:
    name: run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          path: ./src/github.com/${{ github.repository }}

      - name: run
        uses: cedrickring/golang-action@1.4.1