name: Build and test Go
on: push
jobs:
  build:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: run
        uses: cedrickring/golang-action@1.4.1